### PR TITLE
Update the companies using SWC

### PR DESCRIPTION
**Pull request by zhangtao25**
Dear SWC Team,

I am an employee at [Trip.com](https://www.trip.com), and I would like to submit a PR to include Trip.com in the "Who’s using?" section on the SWC website. At Trip.com, we have integrated SWC into our end-to-end (e2e) testing processes, particularly by leveraging our custom [swc-plugin-canyon](https://github.com/canyon-project/canyon/tree/main/plugins/swc-plugin-canyon).

Canyon is a JavaScript code coverage tool tailored for e2e testing. Initially, we developed `babel-plugin-canyon` and `vite-plugin-canyon` to serve our coverage needs. However, after realizing that several of our internal applications built with [Next.js](https://nextjs.org) were using SWC, we extended our solution with [swc-plugin-canyon](https://github.com/canyon-project/canyon/tree/main/plugins/swc-plugin-canyon). This plugin allows us to detect environment variables in our CI pipeline and report code coverage data alongside e2e results, which are then displayed on our internal server.

We are excited to share our use case for SWC at [Trip.com](https://www.trip.com), and we truly appreciate the contributions of the SWC team to the developer community.

Thank you for your consideration.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
It's not an exhaustive list of users. I think adding a customers page is fine, but I think this is not a good idea because there are lots of companies using SWC already and if they all try to write their company name it would be not maintainable

**Comment by zhangtao25** [comment]
> It's not an exhaustive list of users. I think adding a customers page is fine, but I think this is not a good idea because there are lots of companies using SWC already and if they all try to write their company name it would be not maintainable

I see, I'll submit a revision in the near future.

**Comment by kdy1** [comment]
Thank you!

**Comment by zhangtao25** [comment]
> Thank you!

I see you did a whole project refactoring in the morning, this pr is hard to resolve conflicts, I started a new [266](https://github.com/swc-project/website/pull/266)

**Comment by kdy1** [comment]
Closing as https://github.com/swc-project/website/pull/266 is merged!

**Pull request closed without merging**
