### PR TITLE
Add online REPL page

### LINKED ISSUE #6: REPL / playground
I believe that is must-have feature.
Should we organize one @kdy1?

### PR DESCRIPTION
**Pull request by 9oelM**
https://user-images.githubusercontent.com/22465806/123822565-5fe1e300-d937-11eb-84c2-c8e9b90799b8.mp4

This PR adds the long-awaited online REPL on swc's website. Because it's the first one, it just adds the most basic functionality of REPL: compiling the code and showing the output. Nothing really more.

Partly because the website is based on Docusaurus, there are more things to configure right now. For the next commits, following things are expected to be done:

- inserting various options in transpiling
- enlarging the editor (now it's too small because of Docusaurus' default layout)
- running wasm in a separate worker thread
- anything else you'd like

Will close #6 and https://github.com/swc-project/swc/issues/50

### CODE REVIEW

**Comment by 9oelM** [comment]
cc @kdy1

**Comment by kdy1** [comment]
Wow, cool!
Thank you!

Is this PR done? (I'm asking this because of WIP in the title)

**Comment by 9oelM** [comment]
I wasn't too sure if I should append more commits to improve the current PR, so I just marked this PR as draft. It's fine if you want to merge this PR first, and then let me add more commits to improve it.

I'm also not sure if it's going to be successfully built and deployed because i made upgraded some dependencies and there is no preview . But when things break, we can always fix them by then too. haha

**Comment by 9oelM** [comment]
@kdy1 then.. let's merge it first?

**Review by kdy1 — APPROVED** [review]
LHTM. Thanks!

**Pull request merged**
