### PR TITLE
fix: typo in mangle options for class names and functions

### LINKED ISSUE #166: Error unknown field keepClassnames/keepFnames in swc config
## Steps to reproduce

Create swc config file and set keepClassnames and keepFnames of mangle options as described in documentation.

### Expected

Flags should be applied, no errors in terminal

### Actual

Flags are not applied error in the console

> Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: unknown field `keepClassnames`, expected one of `props`, `topLevel`, `keepClassNames`, `keepFnNames`, `keepPrivateProps`, `ie8`, `safari10`, `reserved` at line 1 column 750

### Atachments:

swcrc
```json
{
  "jsc": {
    "target": "es2021",
    "parser": {
      "syntax": "typescript"
    },
    "minify": {
      "compress": {
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "ecma": 2020,
        "evaluate": true,
        "if_return": true,
        "join_vars": true,
        "module": true,
        "negate_iife": true,
        "sequences": true,
        "switches": true,
        "unused": true
      },
      "mangle": {
        "keepClassnames": false,
        "keepFnames": false,
        "keepPrivateProps": false,
        "topLevel": false,
        "reserved": [],
        "properties": {
          "builtins": false,
          "debug": false,
          "keep_quoted": false,
          "regex": null,
          "reserved": [],
          "undeclared": false
        }
      }
    }
  },
  "module": {
    "type": "es6",
    "strict": true,
    "strictMode": true
  }
}
```

### PR DESCRIPTION
**Pull request by kaczor6418**
Fixes #166

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
This is simply wrong.

https://github.com/swc-project/swc/blob/032d58426550f2aacbedc7301add26fa6346c8f9/crates/swc_ecma_minifier/src/option/terser.rs

**Comment by kaczor6418** [comment]
hmmmm, but it gives me an error if I do not change. I will prepare a repository with min code needed to reproduce this

**Comment by kaczor6418** [comment]
@kdy1 please check repository I have attached to [issue description](https://github.com/swc-project/website/issues/166#issue-1244101343)

**Comment by kaczor6418** [comment]
> This is simply wrong.
> 
> https://github.com/swc-project/swc/blob/032d58426550f2aacbedc7301add26fa6346c8f9/crates/swc_ecma_minifier/src/option/terser.rs

It looks like flags from documentation should work, but somehow I am getting an error that such flag is unknown. I have created a repository with min code needed to reproduce this and attached in issue description.

If I am doing sth wrong in my webpack config, please let me know

**Pull request closed without merging**
