### PR TITLE
feat(/): change link from Twitter to GitHub

### PR DESCRIPTION
**Pull request by Sn-Kinos**
On the section, It provides same Twitter link in duplicate so I changed it to GitHub link for providing more information of creator.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Can you change the link text, too?

**Comment by Sn-Kinos** [comment]
> Can you change the link text, too?

Does that mean you want to change it to plain text from link?

**Comment by kdy1** [comment]
Nope, I meant the text shown for the link

**Comment by Sn-Kinos** [comment]
Ahh I got it. I will apply it right now 🏃‍♂️

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
