### PR TITLE
Add user: Tencent

### PR DESCRIPTION
**Pull request by xuqingkuang**
Hi

Tencent is the largest internet company in China, I'm an employee. We are using swc in our projects, it's a pretty fast compiler to make our compile times shorter.

And I wish to add our company logo to the swc users page.

Please approve, here's the preview.

wecom-temp-0b53fdbb8de5b822096d3b3b1351bea2

### CODE REVIEW

**Comment by kdy1** [comment]
Thank you a lot!
I'm really glad to see more swc users. :)

**Comment by xuqingkuang** [comment]
> Thank you a lot!
> I'm really glad to see more swc users. :)

Hi, thank you for the fast response, but I see you are moving the logo to the last.

In fact, the users page should be ordered by some condition, must not be appended only, such as company size, or as the project is open source(pin).

**Comment by kdy1** [comment]
Yes, I think you are right as it's important for marketing(?) of library.
I'll modify it.

**Comment by xuqingkuang** [comment]
> Yes, I think you are right as it's important for marketing(?) of library.
> I'll modify it.

OK, I'm looking forward to the new page.

By the way, in my perception, the 1:1 ratio logos look better and unified.

**Pull request merged**
